name = "survivor-game-server"
main = "src/index.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[env.development.vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production" 